### ISSUE TITLE
On peut parler ici !

### ISSUE THREAD

**Issue by thibaultChatelain** [PolytechLyon/git-5a-g1-git-team#1]
PARLER ICI

**Comment by AlexandreBRUHAT** [comment]
C'est de la triche

**Comment by Cynnexis** [comment]
Non c'est via Git 😋

**Comment by LeaChemoul** [comment]
J'en avait créé une autre dans la team personne répondait Xd

**Comment by LeaChemoul** [comment]
Qui après Val (je précise que le repo est public) ?

**Comment by ProjetInfoIlo** [comment]
Y"a un onglet "discussion" dans team https://github.com/orgs/PolytechLyon/teams/git-team

**Comment by thibaultChatelain** [comment]
j'ai écrit sur la poursuite entre le tueur et le narrateur

**Comment by Cynnexis** [comment]
> Y"a un onglet "discussion" dans team https://github.com/orgs/PolytechLyon/teams/git-team

Après moulte discussion de vive voix, la Direction a décidée que les échanges GitHub se dérouleraient [ici](https://github.com/orgs/PolytechLyon/teams/git-team).
